# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-erb

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Layout/IndentationStyle:
  EnforcedStyle: spaces
  IndentationWidth: 2
  Enabled: true

Layout/IndentationWidth:
  Width: 2
  Enabled: true