source "https://rubygems.org"

# =================
# Rails
# =================
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# Static analysis for security vulnerabilities [https://brakemanscanner.org/]
gem "brakeman", require: false, group: [ :development, :test ]
# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"
# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false
# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# =================
# Middleware
# =================
gem "rack-cors"

# =================
# Data
# =================
# Serializer [https://github.com/okuramasafumi/alba]
gem "alba"

# =================
# Database
# =================
gem "pg", "~> 1.5"

# =================
# Code Quality
# =================
# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false, group: [ :development, :test ]
gem "rubocop-erb", require: false, group: [ :development, :test ]
gem "rubocop-performance", require: false, group: [ :development, :test ]

# =================
# Tools
# =================
gem "metainspector"
gem "annotaterb", group: [ :development, :test ]
gem "web-console", group: [ :development, :test ]
gem "httparty"
# Validation helpers
gem "dry-validation"
# Serializer Backend
gem "oj"
gem "sneakers"
gem "jwt"

# =================
# Caching
# =================
# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache", "~> 1.0.7"
gem "solid_queue", "~> 1.2.1"
gem "solid_cable", "~> 3.0.12"
# Valkey
gem "redis"
# ruby-like syntax for redis objects
gem "redis-objects"
