services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - default
      - proxy_net
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M
    volumes:
      - /mnt/ssd/docker/shortener/rabbit:/var/lib/rabbitmq

  db:
    image: postgres:17
    container_name: postgres
    networks:
      - default
      - proxy_net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/ssd/docker/shortener/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

  cache:
    image: valkey/valkey:8.1.4
    container_name: valkey
    volumes:
      - /mnt/ssd/docker/shortener/valkey:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M
    ports:
      - "6379:6379"
    networks:
      - default
      - proxy_net

networks:
  default:
  proxy_net:
    external: true