services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - default
      - proxy_net
    ports:
      - "15672:15672"
    env_file:
      - /mnt/ssd/docker/shortener/.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M
    volumes:
      - /mnt/ssd/docker/shortener/rabbit:/var/lib/rabbitmq

  db:
    image: postgres:17
    container_name: postgres
    networks:
      - default
    env_file:
      - /mnt/ssd/docker/shortener/.env
    volumes:
      - /mnt/ssd/docker/shortener/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

  cache:
    image: valkey/valkey:8.1.4
    container_name: valkey
  env_file:
      - /mnt/ssd/docker/shortener/.env
  volumes:
      - /mnt/ssd/docker/shortener/valkey:/data
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 1024M
      reservations:
        cpus: '0.5'
        memory: 256M
  ports:
    - "6379:6379"
  networks:
    - default
    - proxy_net

networks:
  default:
  proxy_net:
    external: true