# https://docs.deno.com/runtime/reference/docker/
# Build stage
FROM denoland/deno:2.9.7@sha256:fa335acdf6b72106eda2cb6a8cb5f4187e7630e357467489db4b2e7352d5e432 AS builder
WORKDIR /app
COPY ./edge-function .
RUN deno cache index.ts

# Production stage
FROM denoland/deno:2.9.7@sha256:fa335acdf6b72106eda2cb6a8cb5f4187e7630e357467489db4b2e7352d5e432
WORKDIR /app
COPY --from=builder /app .
CMD ["deno", "run", "--allow-net", "--allow-env", "--allow-read", "index.ts"]
