services:
  frontend:
    image: alexandros-macbook-pro:5001/shortener-frontend:latest
    environment:
      - PORT=80
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  proxy_net:
    external: true
