services:
  frontend:
    image: alexandros-macbook-pro:5001/shortener-frontend:latest
    environment:
      - PORT=80
    ports:
      - "8083:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.hostname == pifive
