services:
  frontend:
    image: alexandros-macbook-pro:5001/shortener-frontend:latest
    environment:
      - PORT=8083
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.hostname == pifive
