services:
  frontend:
    image: shortener-frontend:latest
    ports:
      - "9002:80"
    networks:
      - default
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  default:
  proxy_net:
    external: true