services:
  web: 
    image: shortener:latest
    environment:
      - RAILS_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_URL=${REDIS_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - EDGE_API=${EDGE_API}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_LOGGER=1
    networks:
      - default
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  
  workers: 
    image: shortener:latest
    command: bundle exec rake workers:run
    networks:
      - default
      - proxy_net
    environment:
      - RAILS_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_URL=${REDIS_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SENTRY_DSN=${SENTRY_DSN}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  
  jobs: 
    image: shortener:latest
    command: bin/jobs
    networks:
      - default
      - proxy_net
    environment:
      - RAILS_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_URL=${REDIS_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SENTRY_DSN=${SENTRY_DSN}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  
  serveless:
    image: shortener-edge:latest
    working_dir: /app
    environment:
      - RAILS_ENV=production
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_URL=${REDIS_URL}
    networks:
      - default
      - proxy_net

networks:
  default:
  proxy_net:
    external: true