services:
  web: 
    image: shortener:latest
    env_file:
      - /mnt/ssd/docker/shortener/.env
    networks:
      - default
      - proxy_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  
  jobs: 
    image: shortener:latest
    command: bundle exec rake workers:run
    env_file:
      - /mnt/ssd/docker/shortener/.env
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

networks:
  default:
  proxy_net:
    external: true