# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: safebrowsing.proto

require "google/protobuf"

require "google/protobuf/duration_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("safebrowsing.proto", syntax: :proto3) do
    add_message "google.security.safebrowsing.v5.SearchHashesResponse" do
      repeated :full_hashes, :message, 1, "google.security.safebrowsing.v5.FullHash"
      optional :cache_duration, :message, 2, "google.protobuf.Duration"
    end
    add_message "google.security.safebrowsing.v5.FullHash" do
      optional :full_hash, :bytes, 1
      repeated :full_hash_details, :message, 2, "google.security.safebrowsing.v5.FullHash.FullHashDetail"
    end
    add_message "google.security.safebrowsing.v5.FullHash.FullHashDetail" do
      optional :threat_type, :enum, 1, "google.security.safebrowsing.v5.ThreatType"
      repeated :attributes, :enum, 2, "google.security.safebrowsing.v5.ThreatAttribute"
    end
    add_enum "google.security.safebrowsing.v5.ThreatType" do
      value :THREAT_TYPE_UNSPECIFIED, 0
      value :MALWARE, 1
      value :SOCIAL_ENGINEERING, 2
      value :UNWANTED_SOFTWARE, 3
      value :POTENTIALLY_HARMFUL_APPLICATION, 4
    end
    add_enum "google.security.safebrowsing.v5.ThreatAttribute" do
      value :THREAT_ATTRIBUTE_UNSPECIFIED, 0
      value :CANARY, 1
      value :FRAME_ONLY, 2
    end
  end
end

module Google
  module Security
    module Safebrowsing
      module V5
        SearchHashesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.security.safebrowsing.v5.SearchHashesResponse").msgclass
        FullHash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.security.safebrowsing.v5.FullHash").msgclass
        FullHash::FullHashDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.security.safebrowsing.v5.FullHash.FullHashDetail").msgclass
        ThreatType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.security.safebrowsing.v5.ThreatType").enummodule
        ThreatAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.security.safebrowsing.v5.ThreatAttribute").enummodule
      end
    end
  end
end
